### ISSUE TITLE
using app.info() which is deprecated 

### ISSUE THREAD

**Issue by SteinHeselmans** [sphinx-contrib/doxylink#22]
I get this warning:

```
python3.6/dist-packages/sphinx/application.py:402: RemovedInSphinx20Warning: app.info() is now deprecated. Use sphinx.util.logging instead.
  RemovedInSphinx20Warning)
```

It gets printed right after some doxy-link warnings.

A grep on python libraries:

```
$ cd /usr/local/lib/python3.6/dist-packages
$ grep -r "app.info" .
./sphinxcontrib/doxylink/doxylink.py:        app.info(bold('Checking tag file cache for %s: ' % cache_name), nonl=True)
./sphinxcontrib/doxylink/doxylink.py:            app.info('No cache at all, rebuilding...')
./sphinxcontrib/doxylink/doxylink.py:            app.info('Sub cache is missing, rebuilding...')
./sphinxcontrib/doxylink/doxylink.py:            app.info('Sub-cache is out of date, rebuilding...')
./sphinxcontrib/doxylink/doxylink.py:            app.info('Sub-cache schema version doesn\'t match, rebuilding...')
./sphinxcontrib/doxylink/doxylink.py:            app.info('Sub-cache is up-to-date')
./sphinx/parsers.py:        self.info = app.info
Binary file ./sphinx/__pycache__/application.cpython-36.pyc matches
./sphinx/application.py:        warnings.warn('app.info() is now deprecated. Use sphinx.util.logging instead.',
./sphinx/builders/__init__.py:        self.info = app.info        # type: Callable
```

So this repo needs an update for newer sphinx versions.

**Comment by Pesa** [comment]
This is now causing a hard error with sphinx-2.0.x. Can we get a new release please?

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sphinx/cmd/build.py", line 283, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/usr/local/lib/python3.5/dist-packages/sphinx/application.py", line 260, in __init__
    self._init_builder()
  File "/usr/local/lib/python3.5/dist-packages/sphinx/application.py", line 321, in _init_builder
    self.emit('builder-inited')
  File "/usr/local/lib/python3.5/dist-packages/sphinx/application.py", line 440, in emit
    return self.events.emit(event, self, *args)
  File "/usr/local/lib/python3.5/dist-packages/sphinx/events.py", line 76, in emit
    results.append(callback(*args))
  File "/usr/local/lib/python3.5/dist-packages/sphinxcontrib/doxylink/doxylink.py", line 277, in setup_doxylink_roles
    app.add_role(name, create_role(app, tag_filename, rootdir))
  File "/usr/local/lib/python3.5/dist-packages/sphinxcontrib/doxylink/doxylink.py", line 209, in create_role
    app.info(bold('Checking tag file cache for %s: ' % cache_name), nonl=True)
AttributeError: 'Sphinx' object has no attribute 'info'
```
