### ISSUE TITLE
Incompatibility with Sphinx 2.0.1

### ISSUE THREAD

**Issue by Letme** [sphinx-contrib/doxylink#24]
Sphinx changed the API in 2.0.0 majorly and it all seems that this affects the doxylink plugin as well.

When trying to build same thing with builds on older sphinxes (doc build) I get the error:
```
# Sphinx version: 2.0.1
# Python version: 3.5.3 (CPython)
# Docutils version: 0.14
# Jinja2 version: 2.10.1
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sphinx/cmd/build.py", line 283, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/usr/local/lib/python3.5/dist-packages/sphinx/application.py", line 260, in __init__
    self._init_builder()
  File "/usr/local/lib/python3.5/dist-packages/sphinx/application.py", line 321, in _init_builder
    self.emit('builder-inited')
  File "/usr/local/lib/python3.5/dist-packages/sphinx/application.py", line 440, in emit
    return self.events.emit(event, self, *args)
  File "/usr/local/lib/python3.5/dist-packages/sphinx/events.py", line 76, in emit
    results.append(callback(*args))
  File "/usr/local/lib/python3.5/dist-packages/sphinxcontrib/doxylink/doxylink.py", line 277, in setup_doxylink_roles
    app.add_role(name, create_role(app, tag_filename, rootdir))
  File "/usr/local/lib/python3.5/dist-packages/sphinxcontrib/doxylink/doxylink.py", line 209, in create_role
    app.info(bold('Checking tag file cache for %s: ' % cache_name), nonl=True)
AttributeError: 'Sphinx' object has no attribute 'info'
```

Can anyone give it a glimpse and propose a fix?

**Comment by Letme** [comment]
Hm, seems like fix is in #23 , and I need to update the plugin version.

**Comment by Letme** [comment]
I need a new release to be drafted so that I can install it via pip.

**Comment by milliams** [comment]
Release in incoming.
