### ISSUE TITLE
AttributeError: 'module' object has no attribute 'parse'  in 1.4

### ISSUE THREAD

**Issue by SergioRAgostinho** [sphinx-contrib/doxylink#5]
Hi,

Version 1.4  was just uploaded to pip yesterday and [PCL](https://github.com/PointCloudLibrary/pcl)'s CI started failing with the following exception thrown (see below). I was able to verify the same in my local dev environment .
Our CI runs Ubuntu 14.04 and my local environment 16.04.

**Edit**: I just noticed you set up Travis for python 3.x. Was support for python 2.7 dropped in 1.4? If that's the case this might not be a bug per se.

```
building [mo]: all of 0 po files
building [html]: all source files
updating environment: 98 added, 0 changed, 0 removed
reading sources... [  2%] alignment_prerejective                                                                                               
Exception occurred:
  File "/home/sergio/.local/lib/python2.7/site-packages/sphinxcontrib/doxylink/doxylink.py", line 432, in find_doxygen_link
    if os.path.isabs(rootdir) or urllib.parse.urlparse(rootdir).scheme:
AttributeError: 'module' object has no attribute 'parse'
The full traceback has been saved in /tmp/sphinx-err-esXIV6.log, if you want to report the issue to the developers.
```

Here's the full produced log with the stack trace.
```
# Sphinx version: 1.6.5
# Python version: 2.7.12 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:
#   loading pickled environment...
#   not yet created
#   Checking tag file cache for pcl.tag:
#   No cache at all, rebuilding...
#   building [mo]: all of 0 po files
#   building [html]: all source files
#   updating environment:
#   98 added, 0 changed, 0 removed
#   reading sources... [  1%] adding_custom_ptype
#   reading sources... [  2%] alignment_prerejective
# Loaded extensions:
#   alabaster (0.7.10) from /home/sergio/.local/lib/python2.7/site-packages/alabaster/__init__.pyc
#   sphinxcontrib.doxylink.doxylink (unknown version) from /home/sergio/.local/lib/python2.7/site-packages/sphinxcontrib/doxylink/doxylink.py
#   sphinx.ext.imgmath (1.6.5) from /home/sergio/.local/lib/python2.7/site-packages/sphinx/ext/imgmath.pyc
Traceback (most recent call last):
  File "/home/sergio/.local/lib/python2.7/site-packages/sphinx/cmdline.py", line 306, in main
    app.build(opts.force_all, filenames)
  File "/home/sergio/.local/lib/python2.7/site-packages/sphinx/application.py", line 333, in build
    self.builder.build_all()
  File "/home/sergio/.local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 288, in build_all
    self.build(None, summary='all source files', method='all')
  File "/home/sergio/.local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 344, in build
    updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
  File "/home/sergio/.local/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 584, in update
    self._read_serial(docnames, self.app)
  File "/home/sergio/.local/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 603, in _read_serial
    self.read_doc(docname, app)
  File "/home/sergio/.local/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 726, in read_doc
    pub.publish()
  File "/home/sergio/.local/lib/python2.7/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/home/sergio/.local/lib/python2.7/site-packages/sphinx/io.py", line 74, in read
    self.parse()
  File "/home/sergio/.local/lib/python2.7/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/home/sergio/.local/lib/python2.7/site-packages/docutils/parsers/rst/__init__.py", line 191, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/home/sergio/.local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/home/sergio/.local/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/sergio/.local/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/sergio/.local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2753, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/sergio/.local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/sergio/.local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/home/sergio/.local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/sergio/.local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/sergio/.local/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/sergio/.local/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/sergio/.local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2688, in blank
    context, self.state_machine.abs_line_number() - 1)
  File "/home/sergio/.local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 418, in paragraph
    textnodes, messages = self.inline_text(text, lineno)
  File "/home/sergio/.local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 427, in inline_text
    return self.inliner.parse(text, lineno, self.memo, self.parent)
  File "/home/sergio/.local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 645, in parse
    lineno)
  File "/home/sergio/.local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 787, in interpreted_or_phrase_ref
    lineno)
  File "/home/sergio/.local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 871, in interpreted
    nodes, messages2 = role_fn(role, rawsource, text, lineno, self)
  File "/home/sergio/.local/lib/python2.7/site-packages/sphinxcontrib/doxylink/doxylink.py", line 432, in find_doxygen_link
    if os.path.isabs(rootdir) or urllib.parse.urlparse(rootdir).scheme:
AttributeError: 'module' object has no attribute 'parse'
```

Let me know if you need additional information.

Cheers

**Comment by milliams** [comment]
Hi Sergio,

Indeed Support for Python 2 was dropped in version 1.4, sorry about that. I'll post on your issue tracker about possible solutions for you.

Cheers,
Matt
